{% from "map.jinja" import user,theme with context %}
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

{% if theme == 'powerlevel9k' %}
# https://github.com/bhilburn/powerlevel9k
ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time virtualenv aws kubecontext)
POWERLEVEL9K_PYTHON_ICON='\U1F40D'
{% endif %}

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#plugins=(git ssh-agent virtualenvwrapper zsh-syntax-highlighting)
plugins=(git zsh-syntax-highlighting)

# User configuration

export GOPATH=$HOME/go
export PATH=$HOME/bin:/usr/local/bin:$HOME/go/bin:$HOME/.gem/ruby/2.3.0/bin:$HOME/bin/google-cloud-sdk/bin:/usr/local/lib/node_modules:$PATH

# Reduce keytimeout in order to switch to escape mode faster
export KEYTIMEOUT=1

source $ZSH/oh-my-zsh.sh
which $HOME/bin/google-cloud-sdk/completion.zsh.inc >/dev/null && source $HOME/bin/google-cloud-sdk/completion.zsh.inc
which /usr/local/bin/aws_zsh_completer.sh >/dev/null && source /usr/local/bin/aws_zsh_completer.sh

unsetopt correct_all
setopt interactivecomments

# Do not share history
setopt no_share_history

alias salt-apply="salt-call --local -c etc/salt state.apply"
alias lc='colorls -lA --sd'
alias lct='colorls --tree'
alias lc1='colorls -1'
alias l1='colorls -1'

which dircolors >/dev/null && eval $(dircolors $HOME/.dircolors-solarized/dircolors.256dark)

# Hide the "user@hostname" info when you're logged in as yourself on your local machine
DEFAULT_USER={{ user }}

{% if salt['grains.get']('os') == 'MacOS' %}
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
{% endif %}

export AWS_SDK_LOAD_CONFIG=1
