 " Note: Skip initialization for vim-tiny or vim-small.
 if 0 | endif

 if has('vim_starting')
   if &compatible
     set nocompatible               " Be iMproved
   endif

   " Required:
   set runtimepath+=~/.vim/bundle/neobundle.vim/
 endif

" Required:
call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'

" Bundle
NeoBundle "bling/vim-airline"

" Code
NeoBundle "scrooloose/syntastic"

" Tags
NeoBundle "majutsushi/tagbar"

" Puppet
NeoBundle "nvogel/vim-puppet"

" Groovy
NeoBundle "vim-scripts/groovyindent-unix"

" Color scheme
NeoBundle 'cyplo/vim-colors-solarized'
NeoBundle 'sjl/badwolf'

" File navigation
" https://github.com/ctrlpvim/ctrlp.vim
NeoBundle 'ctrlpvim/ctrlp.vim'

" Set wildignore from git repo root
" https://github.com/octref/RootIgnore
NeoBundle 'octref/RootIgnore'

" An ack/ag powered code search and view tool
" https://github.com/dyng/ctrlsf.vim
NeoBundle 'dyng/ctrlsf.vim'

" Git Plugins
" https://github.com/tpope/vim-fugitive
NeoBundle 'tpope/vim-fugitive'

" Space and Indentation
" https://github.com/ntpeters/vim-better-whitespace
NeoBundle "ntpeters/vim-better-whitespace"

" Markdown
" https://github.com/plasticboy/vim-markdown
NeoBundle "plasticboy/vim-markdown"

" Python
" https://github.com/tweekmonster/braceless.vim
NeoBundle "tweekmonster/braceless.vim"

" Edition
" https://github.com/terryma/vim-multiple-cursors
NeoBundle "terryma/vim-multiple-cursors"

" Search
" https://github.com/haya14busa/incsearch.vim
NeoBundle 'haya14busa/incsearch.vim'

" Salt
" https://github.com/saltstack/salt-vim
NeoBundle 'saltstack/salt-vim'

" Jinja
" https://github.com/Glench/Vim-Jinja2-Syntax
NeoBundle 'Glench/Vim-Jinja2-Syntax'

call neobundle#end()

" Enable loading the indent file for specific file types
:filetype plugin indent on

" Paste
" Pasting text into a terminal running Vim with automatic indentation enabled
" can destroy the indentation of the pasted text.
" This tip shows how to avoid the problem.
" http://vim.wikia.com/wiki/Toggle_auto-indenting_for_code_paste
" :help 'paste'
" :help 'pastetoggle
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>

" Set mapleader to ","
let mapleader = ","

" -----------------------------------------------------------------------------
" Space/Tab/Special characters
" -----------------------------------------------------------------------------

"set listchars=tab:▷⋅,trail:·
" toggle highlight trailing whitespace
"nmap <silent> <leader>s :set nolist!<CR>
nmap <silent> <leader>s :ToggleWhitespace<CR>
" center display after searching
nnoremap n nzz
nnoremap N Nzz

" keep selection after in/outdent
vnoremap < <gv
vnoremap > >gv

" replace tab with spaces
:set expandtab

" number of space characters that will be inserted when the tab key is pressed
:set tabstop=4

" change the number of space characters inserted for indentation
:set shiftwidth=4

" makes the spaces feel like real tabs
:set softtabstop=4

autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab

" disable folding
set nofoldenable


set cursorline " highlight current line

" Enable color syntax highlighting
syntax on

" Colorscheme
:set background=dark
let &t_Co=256 " Force the 256-color mode

" No swapfile & backup
set noswapfile
set nobackup

" Mouse
set ttyfast
set mouse=a
set ttymouse=xterm2

" ------------------------------------------------------------------------------
" Split navigations
" ------------------------------------------------------------------------------
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

set splitbelow
set splitright

" ------------------------------------------------------------------------------
" Set status line
" ------------------------------------------------------------------------------
set laststatus=2 " Show the status line all the time

"80-character line coloring
set colorcolumn=80

" always at least 5 lines visible above the cursor, and 5 lines visible
" below the cursor
:set scrolloff=5

" Needed on osx
set backspace=start,eol,indent

" disable Background Color Erase (BCE) so that
" color schemes work properly when Vim is used inside tmux and GNU screen
" http://superuser.com/questions/399296/256-color-support-for-vim-background-in-tmux
if &term =~ '256color'
  set t_ut=
endif

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck
